Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |vb|
  	vb.memory = "4096"
  end

  config.vm.provision "shell", path: "bootstrap.sh"

end