Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.synced_folder "./airflow", "/airflow", 
    type: "virtualbox",
    owner: "airflow",
    group: "airflow"
  config.vm.provider "virtualbox" do |vb|
  	vb.memory = "1024"
  end

end